SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE ACCESO;
DROP TABLE ACCION;
DROP TABLE AJUSTE_INV_ARTICULO;
DROP TABLE AJUSTE_INV_MATERIA;
DROP TABLE ARTICULO_EXI;
DROP TABLE COTIZACION_DETALLE;
DROP TABLE FACTURA_DETALLE;
DROP TABLE TRASLADO_INV_ARTICULO;
DROP TABLE ARTICULO_TER;
DROP TABLE ARTICULO_CAT;
DROP TABLE ARTICULO_PRE;
DROP TABLE ARTICULO_UNI;
DROP TABLE MATERIA_EXI;
DROP TABLE TRASLADO_INV_MATERIA;
DROP TABLE UBICACION;
DROP TABLE BODEGA;
DROP TABLE INSTALACION;
DROP TABLE FACTURA;
DROP TABLE MATERIA_PRIMA_UTILIZADA;
DROP TABLE ORDEN_DETALLE;
DROP TABLE ORDEN_TRABAJO;
DROP TABLE RECIBO;
DROP TABLE COTIZACION;
DROP TABLE CITA;
DROP TABLE CANAL;
DROP TABLE EMPLEADO;
DROP TABLE CARGO;
DROP TABLE CITA_ESTADO;
DROP TABLE COMPRA_DETALLE;
DROP TABLE COMPRA_GASTO;
DROP TABLE COMPRA;
DROP TABLE PROVEEDOR;
DROP TABLE CIUDAD;
DROP TABLE CLIENTE;
DROP TABLE COTIZACION_ESTADO;
DROP TABLE FACTURA_ESTADO;
DROP TABLE FORMA_PAGO;
DROP TABLE LOG_USUARIO;
DROP TABLE SOLICITUD_MATERIAL_DETALLE;
DROP TABLE SOLICITUD_MATERIAL;
DROP TABLE MATERIA_PRIMA;
DROP TABLE ORDEN_TIPO_TRABAJO;
DROP TABLE ORDEN_TRABAJO_ESTADO;
DROP TABLE PROVINCIA;
DROP TABLE PAIS;
DROP TABLE USUARIO_ROL;
DROP TABLE ROL_SISTEMA;
DROP TABLE SEQNOS;
DROP TABLE SUCURSAL;
DROP TABLE TIEMPO_ENTREGA;
DROP TABLE TIPO_DOCUMENTO;
DROP TABLE TIPO_ORDEN_CORTINA;
DROP TABLE USUARIO;




/* Create Tables */

CREATE TABLE ACCESO
(
	ID_ACCESO INT NOT NULL,
	ID_ROL INT NOT NULL,
	ID_ACCION INT NOT NULL,
	PRIMARY KEY (ID_ACCESO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ACCION
(
	ID_ACCION INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_ACCION)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE AJUSTE_INV_ARTICULO
(
	ID_MOVIMIENTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_CREA DATE NOT NULL,
	ID_TIPO_MOVIMIENTO INT NOT NULL,
	FACTURA_REFERENCIA VARCHAR(10) NOT NULL,
	UBICACION_ORIGEN INT NOT NULL,
	UBICACION_DESTINO INT NOT NULL,
	ID_ARTICULO INT NOT NULL,
	ID_UBICACION INT NOT NULL,
	ID_UBICACION INT NOT NULL,
	PRIMARY KEY (ID_MOVIMIENTO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE AJUSTE_INV_MATERIA
(
	ID_MOVIMIENTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_CREA DATE NOT NULL,
	ID_TIPO_MOVIMIENTO INT NOT NULL,
	FACTURA_REFERENCIA VARCHAR(10) NOT NULL,
	ID_MATERIA INT NOT NULL,
	ID_UBICACION_ORIGEN INT NOT NULL,
	ID_UBICACION_DESTINO INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	PRIMARY KEY (ID_MOVIMIENTO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ARTICULO_CAT
(
	ID_CATEGORIA INT NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID_CATEGORIA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ARTICULO_EXI
(
	CANT_DISPONIBLE INT NOT NULL,
	ID_UBICACION INT NOT NULL,
	ID_ARTICULO INT NOT NULL
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ARTICULO_PRE
(
	ID_ART_PRE INT NOT NULL,
	PRECIO DECIMAL NOT NULL,
	FECHA_DESDE DATE NOT NULL,
	FECHA_HASTA DATE NOT NULL,
	PRIMARY KEY (ID_ART_PRE)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ARTICULO_TER
(
	ID_ARTICULO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	MIN_STOCK INT NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	FECHA_CREA DATETIME NOT NULL,
	CANT_PER_UNIT INT NOT NULL,
	DISPONIBLE_WEB CHAR(2) NOT NULL,
	IMAGEN VARCHAR(50),
	ID_CATEGORIA INT NOT NULL,
	ID_ART_PRE INT NOT NULL,
	PRIMARY KEY (ID_ARTICULO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ARTICULO_UNI
(
	ID_UNIART INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	ID_MATERIA INT NOT NULL,
	PRIMARY KEY (ID_UNIART)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE BODEGA
(
	ID_BODEGA INT NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	ID_SUCURSAL INT NOT NULL,
	FECHA_CREACION DATE,
	USUARIO_CREA VARCHAR(15),
	ID_SUCURSAL INT NOT NULL,
	PRIMARY KEY (ID_BODEGA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE CANAL
(
	ID_CANAL INT NOT NULL,
	DESCRIPCION VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID_CANAL)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE CARGO
(
	ID_CARGO INT NOT NULL,
	VALOR VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID_CARGO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE CITA
(
	ID_CITA INT NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	FECHA_PROGRAMADA DATETIME,
	HORA TIMESTAMP,
	NOMBRE VARCHAR(64) NOT NULL,
	APELLIDO VARCHAR(64) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	DIRECCION VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(64) NOT NULL,
	COMENTARIO VARCHAR(250),
	ID_CANAL INT NOT NULL,
	ID_CITAEST INT NOT NULL,
	ID_EMPLEADO INT NOT NULL,
	PRIMARY KEY (ID_CITA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE CITA_ESTADO
(
	ID_CITAEST INT NOT NULL,
	VALOR VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID_CITAEST)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE CIUDAD
(
	ID_CIUDAD INT NOT NULL,
	VALOR VARCHAR(25) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	ID_PROVINCIA INT NOT NULL,
	PRIMARY KEY (ID_CIUDAD)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE CLIENTE
(
	ID_CLIENTE VARCHAR(16) NOT NULL,
	PRIMER_NOMBRE VARCHAR(32) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(32) NOT NULL,
	PRIMER_APELLIDO VARCHAR(32) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(32) NOT NULL,
	DIRECCION VARCHAR(32) NOT NULL,
	TELEFONO VARCHAR(16) NOT NULL,
	DIR_INS VARCHAR(32) NOT NULL,
	NIT VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_CLIENTE)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE COMPRA
(
	ID_COMPRA INT NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	TOTAL DECIMAL NOT NULL,
	SUMAS DECIMAL NOT NULL,
	IMPUESTO FLOAT NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	FACTURA VARCHAR(10) NOT NULL,
	ID_FORMA_PAGO INT NOT NULL,
	ID_SOLICITUD_MATERIAL INT NOT NULL UNIQUE,
	ID_PROVEEDOR INT NOT NULL,
	PRIMARY KEY (ID_COMPRA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE COMPRA_DETALLE
(
	ID_COMPRA_DETALLE INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL NOT NULL,
	TOTAL DECIMAL NOT NULL,
	ID_COMPRA INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	PRIMARY KEY (ID_COMPRA_DETALLE)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE COMPRA_GASTO
(
	ID_GASTO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	VALOR DECIMAL NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	FECHA_GASTO DATE NOT NULL,
	ID_COMPRA INT NOT NULL
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE COTIZACION
(
	ID_COTIZACION INT NOT NULL UNIQUE,
	RESUMEN DATE NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	MONTO_DESCUENTO DECIMAL NOT NULL,
	TOTAL DECIMAL NOT NULL,
	SUB_TOTAL DECIMAL NOT NULL,
	PORCENTAJE_ANTICIPO INT NOT NULL,
	DIA_VALIDEZ INT NOT NULL,
	PORCENTAJE_DESCUENTO INT NOT NULL,
	ID_CITA INT NOT NULL,
	ID_ESTADO INT NOT NULL,
	ID_TIEMPO_ENTREGA INT NOT NULL,
	PRIMARY KEY (ID_COTIZACION)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE COTIZACION_DETALLE
(
	ID_COTIZACION_DETALLE INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL NOT NULL,
	TOTAL DECIMAL NOT NULL,
	ALTO FLOAT NOT NULL,
	ANCHO FLOAT NOT NULL,
	LARGO FLOAT NOT NULL,
	AREA FLOAT NOT NULL,
	VOLULMEN FLOAT NOT NULL,
	ID_COTIZACION INT NOT NULL UNIQUE,
	ID_ARTICULO INT NOT NULL,
	PRIMARY KEY (ID_COTIZACION_DETALLE)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE COTIZACION_ESTADO
(
	ID_ESTADO INT NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID_ESTADO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE EMPLEADO
(
	ID_EMPLEADO INT NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	CODIGO_EMP VARCHAR(9) NOT NULL UNIQUE,
	ID_CARGO INT NOT NULL,
	ID_USUARIO INT DEFAULT 0 NOT NULL,
	ID_SUCURSAL INT NOT NULL,
	PRIMARY KEY (ID_EMPLEADO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE FACTURA
(
	ID_FACTURA INT NOT NULL,
	FECHA_FACTURA DATE NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	DIRECCION_FACTURA VARCHAR(50) NOT NULL,
	DIRECCION_INSTALACION VARCHAR(50) NOT NULL,
	NIT VARCHAR(25) NOT NULL,
	NCR VARCHAR(25) NOT NULL,
	GIRO VARCHAR(25) NOT NULL,
	SUB_TOTAL DECIMAL NOT NULL,
	DESCUENTO INT NOT NULL,
	MONTO_DESCUENTO DECIMAL NOT NULL,
	TOTAL DECIMAL NOT NULL,
	ID_ORDEN INT NOT NULL,
	ID_ESTADO INT NOT NULL,
	ID_CLIENTE VARCHAR(16) NOT NULL,
	ID_TIPO_DOCUMENTO INT NOT NULL,
	ID_FORMA_PAGO INT NOT NULL,
	PRIMARY KEY (ID_FACTURA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE FACTURA_DETALLE
(
	ID_DETALLE_FACTURA INT NOT NULL,
	MEDIDAS VARCHAR(10) NOT NULL,
	SENTIDO VARCHAR(10) NOT NULL,
	CUBRES VARCHAR(10) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL NOT NULL,
	TOTAL DECIMAL NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_ARTICULO INT NOT NULL,
	PRIMARY KEY (ID_DETALLE_FACTURA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE FACTURA_ESTADO
(
	ID_ESTADO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_ESTADO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE FORMA_PAGO
(
	ID_FORMA_PAGO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_FORMA_PAGO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE INSTALACION
(
	ID_INSTALACION INT NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	FECHA_INSTALACION DATE NOT NULL,
	ID_FACTURA INT NOT NULL UNIQUE,
	ID_EMPLEADO INT NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_EMPLEADO INT NOT NULL,
	PRIMARY KEY (ID_INSTALACION)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE LOG_USUARIO
(
	ID_USUARIO_LOG INT NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT DEFAULT 0 NOT NULL,
	USUARIO VARCHAR(64) NOT NULL,
	FECHA_INGRESO DATETIME NOT NULL,
	HORA_INGRESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	HORA_FIN TIMESTAMP DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (ID_USUARIO_LOG)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE MATERIA_EXI
(
	CANT_DISPONIBLE INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	ID_UBICACION INT NOT NULL
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE MATERIA_PRIMA
(
	ID_MATERIA INT NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
	MIN_STOCK INT NOT NULL,
	MAX_STOCK INT NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	CANT_PER_UNIT INT NOT NULL,
	ID_ARTUNIDAD INT NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	PRIMARY KEY (ID_MATERIA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE MATERIA_PRIMA_UTILIZADA
(
	ID_ORDEN_DETALLE INT NOT NULL,
	CANTIDAD INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	ID_ORDEN_DETALLE INT NOT NULL
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ORDEN_DETALLE
(
	ID_ORDEN_DETALLE INT NOT NULL,
	AREA FLOAT NOT NULL,
	TOTAL DECIMAL(11,0) NOT NULL,
	ROLLO FLOAT NOT NULL,
	TIPO VARCHAR(11) NOT NULL,
	COLOR VARCHAR(11) NOT NULL,
	ALTO FLOAT NOT NULL,
	ANCHO FLOAT NOT NULL,
	LARGO FLOAT NOT NULL,
	VOLUMEN FLOAT NOT NULL,
	CANTIDAD FLOAT NOT NULL,
	ID_ARTICULO INT NOT NULL,
	ID_ORDEN INT NOT NULL,
	PRIMARY KEY (ID_ORDEN_DETALLE)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ORDEN_TIPO_TRABAJO
(
	ID_TIPO_ORDEN INT NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	PRIMARY KEY (ID_TIPO_ORDEN)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ORDEN_TRABAJO
(
	ID_ORDEN INT NOT NULL,
	FECHA_ORDEN DATE NOT NULL,
	MATERIALES_ADICIONALES VARCHAR(50) NOT NULL,
	OBSERVACIONES VARCHAR(50) NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	ID_COTIZACION INT NOT NULL UNIQUE,
	ID_TIPO_ORDEN INT NOT NULL,
	ID_ESTADO INT NOT NULL,
	ID_TIPO_DOCUMENTO INT NOT NULL,
	ID_ORDEN_CORTINA INT NOT NULL,
	ID_CLIENTE VARCHAR(16) NOT NULL,
	PRIMARY KEY (ID_ORDEN)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ORDEN_TRABAJO_ESTADO
(
	ID_ESTADO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_ESTADO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE PAIS
(
	ID_PAIS INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	PRIMARY KEY (ID_PAIS)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE PROVEEDOR
(
	ID_PROVEEDOR INT NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	CONTACTO VARCHAR(20) NOT NULL,
	ID_CIUDAD INT NOT NULL,
	PRIMARY KEY (ID_PROVEEDOR)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE PROVINCIA
(
	ID_PROVINCIA INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	ID_PAIS INT NOT NULL,
	PRIMARY KEY (ID_PROVINCIA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE RECIBO
(
	ID_RECIBO INT NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	FECHA_RECIBO DATE NOT NULL,
	MONTO DECIMAL NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	ID_COTIZACION INT NOT NULL UNIQUE,
	PRIMARY KEY (ID_RECIBO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE ROL_SISTEMA
(
	ID_ROL INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_ROL)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE SEQNOS
(
	BDATOS VARCHAR(30) NOT NULL,
	TABLA VARCHAR(30) NOT NULL,
	SIGUIENTE INT NOT NULL,
	PKEY VARCHAR(30) NOT NULL,
	ID_SEQNOS INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ID_SEQNOS)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE SOLICITUD_MATERIAL
(
	ID_SOLICITUD_MATERIAL INT NOT NULL UNIQUE,
	FECHA_CREACION DATE NOT NULL,
	ID_ESTADO INT NOT NULL,
	FECHA_SOLICITUD DATE NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	SOLICITADO_POR VARCHAR(20) NOT NULL,
	AUTORIZADO_POR VARCHAR(20),
	PREPARADO_POR VARCHAR(20),
	DESPACHADO_POR VARCHAR(20),
	RECIBIDO_POR VARCHAR(20),
	ID_MATERIA INT NOT NULL,
	PRIMARY KEY (ID_SOLICITUD_MATERIAL)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE SOLICITUD_MATERIAL_DETALLE
(
	ID_SOLICITUD_MATERIAL_D INT NOT NULL,
	REGALIA INT NOT NULL,
	MUESTRA INT NOT NULL,
	VENTAS INT NOT NULL,
	REPARACION INT NOT NULL,
	DESTRUCCION INT NOT NULL,
	TOTAL DECIMAL NOT NULL,
	ID_SOLICITUD_MATERIAL INT NOT NULL,
	ID_MATERIA_PRIMA INT NOT NULL,
	ID_SOLICITUD_MATERIAL INT NOT NULL UNIQUE
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE SUCURSAL
(
	ID_SUCURSAL INT NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(25) NOT NULL UNIQUE,
	DIRECCION VARCHAR(50) NOT NULL,
	NIT VARCHAR(20) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(50),
	RUTA_IMAGEN VARCHAR(100),
	FECHA_CREACION DATETIME,
	USUARIO_CREA VARCHAR(10),
	PRIMARY KEY (ID_SUCURSAL)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE TIEMPO_ENTREGA
(
	ID_TIEMPO_ENTREGA INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_TIEMPO_ENTREGA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE TIPO_DOCUMENTO
(
	ID_TIPO_DOCUMENTO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_TIPO_DOCUMENTO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE TIPO_ORDEN_CORTINA
(
	ID_ORDEN_CORTINA INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID_ORDEN_CORTINA)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE TRASLADO_INV_ARTICULO
(
	ID_MOVIMIENTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_CREA DATE NOT NULL,
	ID_TIPO_MOVIMIENTO INT NOT NULL,
	FACTURA_REFERENCIA VARCHAR(10) NOT NULL,
	ID_ARTICULO INT NOT NULL,
	ID_UBICACION_ORIGEN INT NOT NULL,
	ID_UBICACION_DESTINO INT NOT NULL,
	PRIMARY KEY (ID_MOVIMIENTO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE TRASLADO_INV_MATERIA
(
	ID_MOVIMIENTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_CREA DATE NOT NULL,
	ID_TIPO_MOVIMIENTO INT NOT NULL,
	FACTURA_REFERENCIA VARCHAR(10) NOT NULL,
	UBICACION_DESTINO INT NOT NULL,
	ID_UBICACION_ORIGEN INT NOT NULL,
	ID_UBICACION_DESTINO INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	PRIMARY KEY (ID_MOVIMIENTO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE UBICACION
(
	ID_UBICACION INT NOT NULL,
	DESCRIPCION VARCHAR(15) NOT NULL,
	ESTADO CHAR(3) NOT NULL,
	ID_BODEGA INT NOT NULL,
	PRIMARY KEY (ID_UBICACION)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE USUARIO
(
	ID_USUARIO INT DEFAULT 0 NOT NULL,
	SERVICIO INT DEFAULT 1 NOT NULL,
	USUARIO VARCHAR(10) NOT NULL UNIQUE,
	CLAVE_TEMP VARCHAR(64) NOT NULL,
	CLAVE_DEF VARCHAR(64) NOT NULL,
	FECHA_REGISTRO DATETIME,
	FECHA_MODIFICACION DATETIME,
	FECHA_UTL_PWD DATETIME,
	DESCRIPCION VARCHAR(64) NOT NULL,
	ESTADO CHAR(3) DEFAULT 'A' NOT NULL,
	FECHA_UTL_ING DATETIME,
	PRIMARY KEY (ID_USUARIO)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;


CREATE TABLE USUARIO_ROL
(
	ID_USUARIO_ROL INT NOT NULL,
	ID_USUARIO INT DEFAULT 0 NOT NULL,
	ID_ROL INT NOT NULL,
	PRIMARY KEY (ID_USUARIO_ROL)
) DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;



/* Create Foreign Keys */

ALTER TABLE ACCESO
	ADD FOREIGN KEY (ID_ACCION)
	REFERENCES ACCION (ID_ACCION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ARTICULO_TER
	ADD FOREIGN KEY (ID_CATEGORIA)
	REFERENCES ARTICULO_CAT (ID_CATEGORIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ARTICULO_TER
	ADD FOREIGN KEY (ID_ART_PRE)
	REFERENCES ARTICULO_PRE (ID_ART_PRE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AJUSTE_INV_ARTICULO
	ADD FOREIGN KEY (ID_ARTICULO)
	REFERENCES ARTICULO_TER (ID_ARTICULO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ARTICULO_EXI
	ADD FOREIGN KEY (ID_ARTICULO)
	REFERENCES ARTICULO_TER (ID_ARTICULO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COTIZACION_DETALLE
	ADD FOREIGN KEY (ID_ARTICULO)
	REFERENCES ARTICULO_TER (ID_ARTICULO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA_DETALLE
	ADD FOREIGN KEY (ID_ARTICULO)
	REFERENCES ARTICULO_TER (ID_ARTICULO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRASLADO_INV_ARTICULO
	ADD FOREIGN KEY (ID_ARTICULO)
	REFERENCES ARTICULO_TER (ID_ARTICULO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UBICACION
	ADD FOREIGN KEY (ID_BODEGA)
	REFERENCES BODEGA (ID_BODEGA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITA
	ADD FOREIGN KEY (ID_CANAL)
	REFERENCES CANAL (ID_CANAL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLEADO
	ADD FOREIGN KEY (ID_CARGO)
	REFERENCES CARGO (ID_CARGO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COTIZACION
	ADD FOREIGN KEY (ID_CITA)
	REFERENCES CITA (ID_CITA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITA
	ADD FOREIGN KEY (ID_CITAEST)
	REFERENCES CITA_ESTADO (ID_CITAEST)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROVEEDOR
	ADD FOREIGN KEY (ID_CIUDAD)
	REFERENCES CIUDAD (ID_CIUDAD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA
	ADD FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID_CLIENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_TRABAJO
	ADD FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (ID_CLIENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPRA_DETALLE
	ADD FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRA (ID_COMPRA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPRA_GASTO
	ADD FOREIGN KEY (ID_COMPRA)
	REFERENCES COMPRA (ID_COMPRA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COTIZACION_DETALLE
	ADD FOREIGN KEY (ID_COTIZACION)
	REFERENCES COTIZACION (ID_COTIZACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_TRABAJO
	ADD FOREIGN KEY (ID_COTIZACION)
	REFERENCES COTIZACION (ID_COTIZACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECIBO
	ADD FOREIGN KEY (ID_COTIZACION)
	REFERENCES COTIZACION (ID_COTIZACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COTIZACION
	ADD FOREIGN KEY (ID_ESTADO)
	REFERENCES COTIZACION_ESTADO (ID_ESTADO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CITA
	ADD FOREIGN KEY (ID_EMPLEADO)
	REFERENCES EMPLEADO (ID_EMPLEADO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTALACION
	ADD FOREIGN KEY (ID_EMPLEADO)
	REFERENCES EMPLEADO (ID_EMPLEADO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA_DETALLE
	ADD FOREIGN KEY (ID_FACTURA)
	REFERENCES FACTURA (ID_FACTURA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTALACION
	ADD FOREIGN KEY (ID_FACTURA)
	REFERENCES FACTURA (ID_FACTURA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA
	ADD FOREIGN KEY (ID_ESTADO)
	REFERENCES FACTURA_ESTADO (ID_ESTADO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPRA
	ADD FOREIGN KEY (ID_FORMA_PAGO)
	REFERENCES FORMA_PAGO (ID_FORMA_PAGO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA
	ADD FOREIGN KEY (ID_FORMA_PAGO)
	REFERENCES FORMA_PAGO (ID_FORMA_PAGO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AJUSTE_INV_MATERIA
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ARTICULO_UNI
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPRA_DETALLE
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MATERIA_EXI
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MATERIA_PRIMA_UTILIZADA
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOLICITUD_MATERIAL
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRASLADO_INV_MATERIA
	ADD FOREIGN KEY (ID_MATERIA)
	REFERENCES MATERIA_PRIMA (ID_MATERIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MATERIA_PRIMA_UTILIZADA
	ADD FOREIGN KEY (ID_ORDEN_DETALLE)
	REFERENCES ORDEN_DETALLE (ID_ORDEN_DETALLE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_TRABAJO
	ADD FOREIGN KEY (ID_TIPO_ORDEN)
	REFERENCES ORDEN_TIPO_TRABAJO (ID_TIPO_ORDEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA
	ADD FOREIGN KEY (ID_ORDEN)
	REFERENCES ORDEN_TRABAJO (ID_ORDEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_DETALLE
	ADD FOREIGN KEY (ID_ORDEN)
	REFERENCES ORDEN_TRABAJO (ID_ORDEN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_TRABAJO
	ADD FOREIGN KEY (ID_ESTADO)
	REFERENCES ORDEN_TRABAJO_ESTADO (ID_ESTADO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROVINCIA
	ADD FOREIGN KEY (ID_PAIS)
	REFERENCES PAIS (ID_PAIS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPRA
	ADD FOREIGN KEY (ID_PROVEEDOR)
	REFERENCES PROVEEDOR (ID_PROVEEDOR)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIUDAD
	ADD FOREIGN KEY (ID_PROVINCIA)
	REFERENCES PROVINCIA (ID_PROVINCIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACCESO
	ADD FOREIGN KEY (ID_ROL)
	REFERENCES ROL_SISTEMA (ID_ROL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ROL
	ADD FOREIGN KEY (ID_ROL)
	REFERENCES ROL_SISTEMA (ID_ROL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOLICITUD_MATERIAL_DETALLE
	ADD FOREIGN KEY (ID_SOLICITUD_MATERIAL)
	REFERENCES SOLICITUD_MATERIAL (ID_SOLICITUD_MATERIAL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMPRA
	ADD FOREIGN KEY (ID_SOLICITUD_MATERIAL)
	REFERENCES SOLICITUD_MATERIAL_DETALLE (ID_SOLICITUD_MATERIAL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BODEGA
	ADD FOREIGN KEY (ID_SUCURSAL)
	REFERENCES SUCURSAL (ID_SUCURSAL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLEADO
	ADD FOREIGN KEY (ID_SUCURSAL)
	REFERENCES SUCURSAL (ID_SUCURSAL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COTIZACION
	ADD FOREIGN KEY (ID_TIEMPO_ENTREGA)
	REFERENCES TIEMPO_ENTREGA (ID_TIEMPO_ENTREGA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FACTURA
	ADD FOREIGN KEY (ID_TIPO_DOCUMENTO)
	REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_TRABAJO
	ADD FOREIGN KEY (ID_TIPO_DOCUMENTO)
	REFERENCES TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDEN_TRABAJO
	ADD FOREIGN KEY (ID_ORDEN_CORTINA)
	REFERENCES TIPO_ORDEN_CORTINA (ID_ORDEN_CORTINA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AJUSTE_INV_ARTICULO
	ADD FOREIGN KEY (ID_UBICACION)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AJUSTE_INV_ARTICULO
	ADD FOREIGN KEY (ID_UBICACION)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AJUSTE_INV_MATERIA
	ADD FOREIGN KEY (ID_UBICACION_ORIGEN)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AJUSTE_INV_MATERIA
	ADD FOREIGN KEY (ID_UBICACION_DESTINO)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MATERIA_EXI
	ADD FOREIGN KEY (ID_UBICACION)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRASLADO_INV_ARTICULO
	ADD FOREIGN KEY (ID_UBICACION_ORIGEN)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRASLADO_INV_ARTICULO
	ADD FOREIGN KEY (ID_UBICACION_DESTINO)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRASLADO_INV_MATERIA
	ADD FOREIGN KEY (ID_UBICACION_ORIGEN)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRASLADO_INV_MATERIA
	ADD FOREIGN KEY (ID_UBICACION_DESTINO)
	REFERENCES UBICACION (ID_UBICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMPLEADO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID_USUARIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOG_USUARIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID_USUARIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ROL
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID_USUARIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



